apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name | default "dstack" }}-pvc
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
