apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name | default "dstack" }}-service
  labels:
    app: {{ .Values.app.name | default "dstack" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name | default "dstack" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
