{{- if .Values.monitoring.enabled }} 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  endpoints:
  - port: http
    path: /metrics
  interval: 15s
{{- end }}
