{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # Используем переменную имени
  name: {{ .Values.app.name | default "dstack" }}-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      # Ищем поды по той же переменной имени
      app: {{ .Values.app.name | default "dstack" }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
{{- end }}
