
replicaCount: 1

image:
  repository: dstackai/dstack
  pullPolicy: IfNotPresent
  
  tag: "latest"


service:
  type: NodePort
  port: 80           
  targetPort: 3000   
  nodePort: 30080   


ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: dstack.local
      paths:
        - path: /
          pathType: Prefix


storage:
  size: 1Gi
  accessMode: ReadWriteOnce


env:
  DSTACK_ENABLE_PROMETHEUS_METRICS: "true"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

monitoring:
  enabled: true
